{% set name = "libbraiding" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/miguelmarco/libbraiding/archive/{{ version }}.tar.gz
  sha256: 187e1284bf7ba2bb138d042fce8efb089a0f6903718c9c26a1d8a49086ccc3fa

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libbraiding", max_pin="x.") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libbraiding${SHLIB_EXT}
    - test -f $PREFIX/include/braiding.h

about:
  home: https://github.com/miguelmarco/libbraiding
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: cbraid/braiding are C++ libraries for computations on braid groups
  dev_url: https://github.com/miguelmarco/libbraiding

extra:
  recipe-maintainers:
    - isuruf
