{% set name = "libbraiding" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/enriqueartal/libbraiding/archive/{{ version }}.tar.gz
  sha256: sha256:334b401f0903f55f7b7cc62efd4e63b1d38b5f6dd8082c6e0e0a3f68ca99055f
  patches:
    - s.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("libbraiding", max_pin="x.") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - autoconf
    - automake
    - libtool
    - m4
    - make
    - pkg-config
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libbraiding${SHLIB_EXT}
    - test -f $PREFIX/include/braiding.h

about:
  home: https://github.com/miguelmarco/libbraiding
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: cbraid/braiding are C++ libraries for computations on braid groups
  dev_url: https://github.com/miguelmarco/libbraiding

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
