travis:
  secure:
    BINSTAR_TOKEN: fTYpWlJQiq/kwPHVTCa++bJECHnnxCbz/pNgx+a7b36s1EVbu4gXBkA0Qp6V1re9idAsFx3/C22Hpux0s2BTC7TeqzL5J5X1dhd77bzNOQdfGCtjARsvwvckIOuOOlinDSd79P/5lKyG8N3CGhfvizp8TaL+u4gBM5pKk3H9i3RHbWI5tPQzOgPh4HtYXAkuuRqCbmcvTsjliNmDgFXG71IY+kjh4PsGlmp98qlnvqmCNEMFO2meucJiPhguyWCzoEsj0vYuSWG5rpbYLWAHYUdRgdQW+C07hCK/Mc9YLJvK2l80Bz4VBsnt6LHNlylOFdhSEOoQWzBIS0e4knr5vbOHBD++Yaj4Uu6v1jR5rdfaIVzdUFmaqvOFZnDRSQFM3pjtxM7sj6FHFlakrgFJ8TIKT5sQQvPQ6m/KnL76M75EULMWulHJO76QsKwIQ7zT6eG0VNP+qgamGXWNjI6RCxHHoXzpKN1KWz4gk4DpQdpy/AyuhLf/KwKhvFDFfmZVIuZzdf7d5SxN08tAIdQtTLO9r0qgPBZ0JzYOM2tmssJaeIcM3vzm0kTU8VdjGo5O+FZFYfou3ZEauguTzaRx4Ux9ggXY/4MSy9VRWLuXQN/yCPLrDMvbn84wP5iKciFy88Y45bl76FGIHm+tcIDVWIPNCr6AqKbHM+WMPLnPjl4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
